// Create User (Register)
POST http://localhost:5000/users
Content-Type: application/json

{
    "name": "levi",
    "email": "levi@gmail.com",
    "password": "123",
    "confPassword": "123",
    "role": "admin"
}

###
// get All Users
GET http://localhost:5000/users 

###
// get Single User
GET http://localhost:5000/users/d7b5d6c2-64ba-4314-9fe5-bc3a9eb28873

###
// Update User
PATCH  http://localhost:5000/users/96cad46f-ba00-4208-91b3-cb5ae85c0bfc
Content-Type: application/json

{
    "name": "rere",
    "email": "rere@gmail.com",
    "password": "",
    "confPassword": "",
    "role": "pencari kost" 
}

###
// delete user
DELETE http://localhost:5000/users/c6886471-54dc-4f81-96ce-61a0cbf9d941

###
// Login Admin
POST http://localhost:5000/login
Content-Type: application/json

{
    "email": "levi@gmail.com",
    "password": "123"
}

###
// Login Pemilik Kost
POST http://localhost:5000/login
Content-Type: application/json

{
    "email": "sasa@gmail.com",
    "password": "123"
}

###
// Login Pencari Kost
POST http://localhost:5000/login
Content-Type: application/json

{
    "email": "rere@gmail.com",
    "password": "123"
}

###
// me
GET http://localhost:5000/me

###
// logout user
DELETE http://localhost:5000/logout

###
// get all Kost
GET http://localhost:5000/rumah-kost

###
// get single Kost
GET http://localhost:5000/rumah-kost/7295b05b-a925-42b4-81ac-7ab829969687

###
// tambah Kost
POST http://localhost:5000/rumah-kost
Content-Type: application/json

{
    "nama_kost": "hello Kitty",
    "no_hp": "08523989789",
    "desa": "Air Putih",
    "alamat": "Jl. Bathin aja",
    "jk": "putri"
}

###
// update data Kost
PATCH http://localhost:5000/rumah-kost/fa284aa3-a99f-40bd-a966-ebabda35b884
Content-Type: application/json

{
    "nama_kost": "sweety Kitty banget",
    "no_hp": "08520989099",
    "desa": "Sungai Alam",
    "alamat": "Jl. Bathin alam",
    "jk": "putra"
}

###
// delete kost
DELETE http://localhost:5000/rumah-kost/a0e8774e-8333-4a35-8aaf-8cc85f439bda

###
// Rekomendasi Kost
GET http://localhost:5000/rekomendasi-kost

###
// create tipe kamar
POST http://localhost:5000/tipe-rumah-kost/
Content-Type: application/json

{
"f_kamar": "ada ada aja",
"f_umum": "Wifi",
"peraturan_kost": "di larang merokok",
"catatan_tambahan": "",
"foto_kost": "lala.apagitu",
"jumlah_kamar": "3",
"ukuran_kamar": "3x3",
"harga": "300000"
}

###
// get all tipe kamar
GET http://localhost:5000/tipe-rumah-kost/
