// Create User (Register)
POST http://localhost:5000/users
Content-Type: application/json

{
    "name": "dede",
    "email": "dede@gmail.com",
    "password": "123",
    "confPassword": "123",
    "role": "user"
}

###
// get All Users
GET http://localhost:5000/users 

###
// get Single User
GET http://localhost:5000/users/d7b5d6c2-64ba-4314-9fe5-bc3a9eb28873

###
// Update User
PATCH  http://localhost:5000/users/96cad46f-ba00-4208-91b3-cb5ae85c0bfc
Content-Type: application/json

{
    "name": "rere",
    "email": "rere@gmail.com",
    "password": "",
    "confPassword": "",
    "role": "pencari kost" 
}

###
// delete user
DELETE http://localhost:5000/users/c6886471-54dc-4f81-96ce-61a0cbf9d941

###
// Login Admin
POST http://localhost:5000/login
Content-Type: application/json

{
    "email": "levi@gmail.com",
    "password": "123"
}

###
// Login Pemilik Kost
POST http://localhost:5000/login
Content-Type: application/json

{
    "email": "sasa@gmail.com",
    "password": "123"
}

###
// Login Pencari Kost
POST http://localhost:5000/login
Content-Type: application/json

{
    "email": "rere@gmail.com",
    "password": "123"
}

###
// me
GET http://localhost:5000/me

###
// logout user
DELETE http://localhost:5000/logout

###
// get all Kost
GET http://localhost:5000/rumah-kost

###
// get single Kost
GET http://localhost:5000/rumah-kost/7295b05b-a925-42b4-81ac-7ab829969687

###
// tambah data Kost
POST http://localhost:5000/rumah-kost
Content-Type: application/json

{
    "name": "sweety Kitty",
    "no_hp": "08520989099",
    "desa": "Sungai Alam",
    "alamat": "Jl. Bathin alam",
    "gender": "perempuan",
    "f_kamar": "Ac",
    "s_kamar": "3x3",
    "f_kamar_mandi": "wc terbang",
    "f_umum": "Wifi",
    "f_parkir": "sepeda",
    "peraturan_kost": "dilarang merokok",
    "cerita_pemmilik_kost": "kos berhantu",
    "catatan_tambahan": "air hujan",
    "maps": "",
    "foto_kost": "foto.jpg aja",
    "price": "600000"
}

###
// update data Kost
PATCH http://localhost:5000/rumah-kost/82a53fe8-70e9-40b8-8239-b3ba8ecd14d2
Content-Type: application/json

{
    "name": "kost donal itik",
    "no_hp": "085278685008",
    "desa": "Air Putih",
    "alamat": "Jl. Bathin alam",
    "gender": "perempuan",
    "f_kamar": "Ac",
    "s_kamar": "3x3",
    "f_kamar_mandi": "wc jongkok",
    "f_umum": "Wifi",
    "f_parkir": "sepeda",
    "peraturan_kost": "dilarang merokok",
    "cerita_pemmilik_kost": "",
    "catatan_tambahan": "",
    "maps": "",
    "foto_kost": "foto.jpg aja",
    "price": "500000"
}

###
// delete kost
DELETE http://localhost:5000/rumah-kost/a0e8774e-8333-4a35-8aaf-8cc85f439bda

###
// Rekomendasi Kost
GET http://localhost:5000/rekomendasi-kost